import { Metadata } from "next";
import Navbar from "./navbar";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

const interFont = Inter ({
    subsets: ["latin"]
})
export default function Layout( {children}: Readonly<{children: React.ReactNode;}>) {
    return (
        <section>
            {children}
            <Navbar selected={0}/>
        </section>
    )
}